### ISSUE TITLE
[Feature Request]: Add `[AllowNull]` to a controls `Text` field

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#756]
Part of the improvements in .net 6 / 7:
![image](https://user-images.githubusercontent.com/2418812/174472939-46629ccf-d934-416e-a646-a9aa2335cc21.png)

from here:
https://github.com/dotnet/winforms/commit/48616c47095149309b95caea9cc4e7c182313756

**Comment by Wagnerp** [comment]
Making the project 'nullable' should help with this

**Comment by Smurf-IV** [comment]
As part of this merge
https://github.com/Krypton-Suite/Standard-Toolkit/pull/933

The `AllowNull`able  attribute is now backward compatible with previous frameworks.

This will fix most of the following warnings in the compile:
![image](https://user-images.githubusercontent.com/2418812/216764619-6211bc9e-b4cc-4f16-aa3a-ca06c49a978c.png)

**Comment by Wagnerp** [comment]
Reminder!!!!! This _should_ ought to be part of the extended toolkit as well ;)

**Comment by Wagnerp** [comment]
![image](https://user-images.githubusercontent.com/949607/216767231-dc4a9623-c845-467c-90b8-a30a1a515059.png)

**Comment by Wagnerp** [comment]
@Smurf-IV Disable `CS0436`?

**Comment by Smurf-IV** [comment]
> ![image](https://user-images.githubusercontent.com/949607/216767231-dc4a9623-c845-467c-90b8-a30a1a515059.png)

The following should be preventing is from appearing in anything above core 3.1:
`#if NETFRAMEWORK || NETCOREAPP`
????

**Comment by Smurf-IV** [comment]
> @Smurf-IV Disable `CS0436`?

I'll check what Frameworks I have installed; to make sure it is just the supported list ;-)

**Comment by Smurf-IV** [comment]
Seems to be okay, I do not get the following

> @Smurf-IV Disable `CS0436`?

![image](https://user-images.githubusercontent.com/2418812/216771219-a72db341-809e-411f-954c-3342b505df59.png)

**Comment by Smurf-IV** [comment]
@Wagnerp Why is there still netcoreapp3.1 in the Krypton support list ?

![image](https://user-images.githubusercontent.com/2418812/216771625-a268bcd2-c6a1-49ec-bea2-3b7018555243.png)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Disable `CS0436`?

This was caused by the following code
![image](https://user-images.githubusercontent.com/2418812/216771737-5f43b9e7-2d6e-4e29-9a77-280b21ca0336.png)


I'll fix it. (No idea why it was not showing up until I did a full rebuild !!

**Comment by Wagnerp** [comment]
> @Wagnerp Why is there still netcoreapp3.1 in the Krypton support list ?
> 
> ![image](https://user-images.githubusercontent.com/2418812/216771625-a268bcd2-c6a1-49ec-bea2-3b7018555243.png)

@Smurf-IV I'll remove it in the next PR

**Comment by Smurf-IV** [comment]
Oh, wow.. This is turning into a big PR..
Following all the `nullable` entries around the code is also "catching / pointing out" some unexpected locations where things could/will have gone awry.

**Comment by Smurf-IV** [comment]
### As of 2023-02-06:
Changed **All** Standard toolkit projects to be 
- [x] `<LangVersion>preview</LangVersion>`
- [x] `<Nullable>enable</Nullable>`
- [x] `<WarningLevel>6</WarningLevel>`
- [x] `<Optimize>True</Optimize>` for release style builds (i.e. nightly, canary, as well as normal release) 
- [x] Search for API's that return `null` and sett there type to be nullable, e.g. 
  - ![image](https://user-images.githubusercontent.com/2418812/218252658-eb8f7182-9938-40c4-91f6-7cfa96146385.png)
- [x] Trace back those API's and ensure nullabel is applied to all derived API's
- [x] Check all API's that Force return null and set to nullable type, e.g.
  - ![image](https://user-images.githubusercontent.com/2418812/218252717-e290b78e-fc7e-4540-8b43-4ce1d1b201ee.png)

### ToDo:
- [ ] Search ALL API's that check for null and make there parameter(s) nullable
- [ ] Search all code that is accepting the API return types and set there local var to be nullable
- [ ] Attempt to fix as many of these as possible: 
![image](https://user-images.githubusercontent.com/2418812/218252789-99e3e7d6-a914-4168-91dc-89d6fee55537.png)
- [ ] Other code fixes when it shows that a check for null should have been done now that the code is actually stating that the API could return null ! (Catch those edge conditions !!)

**Comment by Smurf-IV** [comment]
Note: The warnings and the enablement of these "Nullable" items will be ongoing, as other Features and Bugs are being worked on.

**Comment by Smurf-IV** [comment]
This may appear to be "dragging on"
But even this past week MS are still pushing PR's into WinForms that are dealing with nullables ;-)
